squidguard:
  # either - build your git clone:
  #build: .
  # or use the image from docker hub:
  image: pfunkmallone/docker-squidguard:latest
  environment:
    # WPAD is optional 
    - WPAD_IP=192.168.99.100
    - WPAD_NOPROXY_NET=192.168.0.0
    - WPAD_NOPROXY_MASK=255.255.0.0
    #- UPDATE_WHITELIST_URL=http://www.shallalist.de/Downloads/shallalist.tar.gz
    #- SQUID_UID=1000          # workaround for folder mapping problem on MAC OS: UserID for user proxy
    # if you need your customized wpad.dat or block.html file, 
    #    simply place them to your host volume that is mapped to SQUID_CONFIG_SOURCE
  ports:
    - "3128:3128"
    - "80:80"
  expose:
    - 3128
    - 80
