#!/bin/bash
set -e

if [  "${UPDATE_WHITELIST_URL}" != "" ]; then
	sudo wget -O whitelist.tar.gz ${UPDATE_WHITELIST_URL} \
 		&& tar -xzf whitelist.tar.gz -C /var/lib/squidguard/db \
 		&& rm whitelist.tar.gz \
 		&& chown proxy:proxy /var/lib/squidguard/db -R
fi

if [ ! -f /etc/squidguard/squidGuard.conf ]; then
	# if this file doesn't exist -> it is the first time
	if [  "${SQUID_UID}" != "" ]; then
		# workaround for mac os mapping problem:
		sudo usermod -u ${SQUID_UID} proxy
	fi
	# chown is required especially because directories can be mapped
	chown -R proxy:proxy /var/lib/squidguard/db /sample-config-denyeverthing /sample-config-whitelist /custom-config /var/log/squid3

	if [  "${UPDATE_WHITELIST_URL}" != "" ]; then
	    echo "no configuration found -> use /sample-config-whitelist"
		ln -s /sample-config-whitelist/squidGuard.conf /etc/squidguard/squidGuard.conf
	else
	    echo "no configuration found -> use /sample-config-denyeverything"
		ln -s /sample-config-denyeverything/squidGuard.conf /etc/squidguard/squidGuard.conf
	fi
fi

echo "running startSquidGuard with WPAD_IP=${WPAD_IP} WPAD_NOPROXY_NET=${WPAD_NOPROXY_NET} WPAD_NOPROXY_MASK=${WPAD_NOPROXY_MASK}"

if [  "${SQUID_CONFIG_SOURCE}" != "" ]; then
	if [ -f ${SQUID_CONFIG_SOURCE}/wpad.dat ]; then
		cp ${SQUID_CONFIG_SOURCE}/wpad.dat /var/www/html/
	else
		echo "wpad file ${SQUID_CONFIG_SOURCE}/wpad.dat does not exist. Use existing file."
	fi
	if [ -f ${SQUID_CONFIG_SOURCE}/block.html ]; then
		cp ${SQUID_CONFIG_SOURCE}/block.html /var/www/html/
	else
		echo "wpad file ${SQUID_CONFIG_SOURCE}/wpad.dat does not exist. Use existing file."
	fi
fi

if [  "${WPAD_IP}" != "" ]; then
	sed 's/{{WPAD_IP}}/'"${WPAD_IP}"'/' -i /var/www/html/wpad.dat
	sed 's/{{WPAD_NOPROXY_NET}}/'"${WPAD_NOPROXY_NET}"'/' -i /var/www/html/wpad.dat
	sed 's/{{WPAD_NOPROXY_MASK}}/'"${WPAD_NOPROXY_MASK}"'/' -i /var/www/html/wpad.dat
fi

# start apache to serve wpad.dat file and or block.html
sudo /etc/init.d/apache2 restart

# run original squid start script
exec /sbin/entrypoint.sh
